spring:
  application:
    name: HelloClient

server:
  port: 7211

hystrix:
  command:
    default:
      fallback:
        enabled: false

feign:
  hystrix:
    enabled: true
  httpclient:
    connectionTimeout: 3000
  client:
    config:
      default:
        readTimeout: 780000
      serviceName:
        connectTimeout: 300
        readTimeout: 3000